stages:
  data_ingestion:
    cmd: python src/data/make_dataset.py
    deps:
    
    - src/data/make_dataset.py
    outs:
    - data/interim/
  feature_eng:
    cmd: python src/features/build_features.py
    deps:
    - data/interim/
    - src/features/build_features.py
    outs:
    - data/processed/
  model_training:
    cmd: python src/models/train_model.py
    deps:
    - data/processed/
    - src/models/train_model.py
    params:
    - model_training.n_estimator
    outs:
    - models/model.pkl
  metrics:
    cmd: python src/models/predict_model.py
    deps:
    - data/processed/
    - models/model.pkl
    - src/models/predict_model.py
    metrics:
    - metrics.json
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
